// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmtvyvtolcrhehqswlxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtdHZ5dnRvbGNyaGVocXN3bHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMzA3NzgsImV4cCI6MjA1ODkwNjc3OH0.gCzLG3fXiAdyCmMnWRCBYm-2ZW1zlHUHxxxpJlpCF4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);